version = 1
name = "magnet-relay"

[setup]
script = ""

[[actions]]
name = "Run"
icon = "run"
command = "python3 scripts/run.py"

[[actions]]
name = "Run Mac"
icon = "run"
command = "python3 scripts/run.py --platform mac"

[[actions]]
name = "Run iOS"
icon = "run"
command = "python3 scripts/run.py --platform ios"
